# Generated by Django 6.0.3 on 2026-05-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_slot',
            new_name='timeslot',
        ),
    ]
